- hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: Update packages cache
    apt:
      update_cache: yes
  - name: Install packages
    apt:
      name: [
        'borgbackup', 
        'htop', 
        'neovim', 
        'wget', 
        'unzip', 
        'rsync', 
        'screen', 
      ]
      state: present
      update_cache: yes
  - name: Remove snapd from Ubuntu
    apt:
      name: snapd
      state: absent
      purge: yes
  - name: Remove snapd-related directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /snap
      - /var/snap
      - /var/lib/snapd
  roles:
    - robertdebock.fail2ban